name: CI with Cache

on:
  push:
    branches:
      - main
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache dependencies
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/mydeps
          key: cache-3173269

      # Step to show cache hit/miss
      - name: prime-cache-3173269
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"
